version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to yml!"

  say-bye:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Say bye to yml!"

workflows:
  hello_and_goodbye:
    jobs:
      - say-hello
      - say-bye